-- ==============================================================================
-- SCHEMA SUPABASE - MANU3D (V2.0)
-- Exécutez ce script dans l'éditeur SQL de Supabase pour créer/mettre à jour les tables.
-- ==============================================================================

-- 1. CONFIGURATION DU SITE (Textes dynamiques, Hero, Facturation)
create table if not exists site_config (
  key text primary key,
  value text not null,
  description text
);

-- Données initiales Config
insert into site_config (key, value, description) values
  ('hero_title1', 'Donnez vie à', 'Ligne 1 du titre Hero'),
  ('hero_title2', 'vos passions', 'Ligne 2 du titre Hero'),
  ('hero_subtitle', 'Impression 3D résine haute définition, Figurines et Décoration Geek.', 'Sous-titre Hero'),
  ('hero_badge', 'Basé à Montivilliers (76)', 'Badge Hero'),
  ('hero_cta_primary', 'Découvrir la Boutique', 'Bouton 1'),
  ('hero_cta_secondary', 'Service sur mesure', 'Bouton 2'),
  ('promo_text', '💥 OFFRE DE LANCEMENT : -15% sur tout le rayon Figurine avec le code MANU15 !', 'Bandeau Promo'),
  ('promo_active', 'true', 'Afficher le bandeau promo (true/false)'),
  ('promo_link', '#shop', 'Lien du bandeau promo'),
  ('shipping_free_threshold', '100', 'Seuil frais de port offerts (en €)'),
  ('invoice_company_name', 'Manu3D', 'Nom entreprise facture'),
  ('invoice_address_line1', 'Montivilliers (76), Normandie', 'Adresse ligne 1'),
  ('invoice_address_line2', 'France', 'Adresse ligne 2'),
  ('invoice_siret', 'SIRET : 000 000 000 00000', 'Numéro SIRET'),
  ('invoice_email', 'contact@manu3d.fr', 'Email contact facture'),
  ('invoice_footer_text', 'TVA non applicable, article 293 B du CGI.', 'Pied de page facture')
on conflict (key) do nothing;

-- 2. CREATEURS / ARTISTES
create table if not exists creators (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text,
  avatar_url text,
  banner_url text,
  website_url text,
  social_instagram text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

insert into creators (name, bio) values ('ABC3D', 'Designers de reliefs muraux Pokemon.') on conflict do nothing;

-- 3. PRODUITS (BOUTIQUE)
create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null, -- 'Figurine', 'Decor', 'Cosplay'
  price text not null, -- Ex: '24.00€' (legacy display)
  numeric_price numeric, -- Ex: 24.00 (pour calculs)
  image text,
  description text,
  rarity text default 'common',
  is_new boolean default false,
  weight_g integer default 100, -- Poids pour expédition
  stock integer default 5,
  creator_id bigint references creators(id),
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. MATERIAUX D'IMPRESSION (POUR LE CONFIGURATEUR B2B)
create table if not exists printing_materials (
  id text primary key, -- ex: 'pla-orange', 'resin-grey'
  name text not null,
  type text not null, -- 'STANDARD' (FDM) ou 'RESINE' (SLA)
  density numeric not null, -- g/cm3 (ex: 1.24 pour PLA)
  cost_per_gram numeric not null, -- coût matière (ex: 0.15)
  color_hex text default 'FFFFFF',
  active boolean default true
);

insert into printing_materials (id, name, type, density, cost_per_gram, color_hex) values
  ('pla-orange', 'PLA Premium (Orange)', 'STANDARD', 1.24, 0.15, 'F39C12'),
  ('resin-grey', 'Résine 8K (Gris)', 'RESINE', 1.15, 0.35, '808080'),
  ('resin-clear', 'Résine Translucide', 'RESINE', 1.18, 0.45, 'AEEEEE')
on conflict (id) do nothing;

-- 5. COUPONS DE REDUCTION
create table if not exists coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  value numeric not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

insert into coupons (code, discount_type, value) values ('MANU15', 'percent', 15) on conflict do nothing;

-- 6. MODES DE LIVRAISON
create table if not exists shipping_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  base_price numeric not null, -- Prix de base
  price_per_kg numeric default 0, -- Supplément par Kg
  is_pickup boolean default false, -- Si true, c'est du retrait (gratuit)
  estimated_days text,
  active boolean default true
);

insert into shipping_methods (name, description, base_price, price_per_kg, is_pickup, estimated_days) values
  ('Retrait Atelier', 'Montivilliers (76)', 0, 0, true, 'Sur RDV'),
  ('Mondial Relay', 'Point Relais', 4.90, 1.00, false, '3-5 jours'),
  ('Colissimo', 'Domicile sans signature', 7.90, 2.00, false, '48h')
on conflict do nothing;

-- 7. COMMANDES (ORDERS)
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  customer_name text,
  customer_email text,
  shipping_address text,
  total_amount numeric,
  shipping_cost numeric,
  discount_amount numeric,
  coupon_code text,
  shipping_method_text text,
  items_json jsonb, -- Stocke le panier complet
  payment_status text default 'pending', -- 'pending', 'paid', 'pending_manual'
  order_status text default 'new' -- 'new', 'processing', 'shipped'
);

-- 8. PARTENAIRES & LICENCES
create table if not exists partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  description text,
  url text,
  display_order integer default 0
);

-- 9. AVIS CLIENTS
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  rating integer,
  text text,
  item_purchased text,
  display_date text,
  active boolean default true
);

-- 10. PORTFOLIO
create table if not exists portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image text,
  display_order integer default 0
);

-- ==============================================================================
-- POLITIQUES DE SÉCURITÉ (RLS) - PUBLIC READ ONLY
-- ==============================================================================

alter table site_config enable row level security;
create policy "Public read config" on site_config for select using (true);

alter table products enable row level security;
create policy "Public read products" on products for select using (true);

alter table printing_materials enable row level security;
create policy "Public read materials" on printing_materials for select using (true);

alter table coupons enable row level security;
create policy "Public read coupons" on coupons for select using (true);

alter table shipping_methods enable row level security;
create policy "Public read shipping" on shipping_methods for select using (true);

alter table partners enable row level security;
create policy "Public read partners" on partners for select using (true);

alter table reviews enable row level security;
create policy "Public read reviews" on reviews for select using (true);

alter table portfolio enable row level security;
create policy "Public read portfolio" on portfolio for select using (true);

alter table creators enable row level security;
create policy "Public read creators" on creators for select using (true);

-- Pour les commandes : Tout le monde peut insérer (pour passer commande), mais personne ne peut lire (sauf admin via dashboard supabase)
alter table orders enable row level security;
create policy "Public insert orders" on orders for insert with check (true);

-- (Optionnel) Pour l'outil Admin (AdminTool.tsx), si tu veux activer l'écriture depuis le site
-- Il faudrait configurer l'authentification Supabase, mais pour l'instant l'outil admin utilise un mot de passe frontend simple.
-- Si tu veux que l'admin puisse écrire, désactive RLS temporairement ou ajoute des policies "anon" (moins sécurisé).
-- create policy "Public write config" on site_config for all using (true);
-- create policy "Public write coupons" on coupons for all using (true);
