-- ==============================================================================
-- SCHEMA SUPABASE - MANU3D ULTIMATE
-- Script de structure complète et sécurisée (RLS Enabled)
-- ==============================================================================

-- 1. CONFIGURATION DU SITE (Clé/Valeur)
CREATE TABLE IF NOT EXISTS site_config (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT
);
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;

-- 2. PRODUITS
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT DEFAULT 'Figurine',
    price TEXT DEFAULT '0.00€',
    image TEXT,
    gallery TEXT[] DEFAULT '{}',
    description TEXT,
    tags TEXT[] DEFAULT '{}',
    is_new BOOLEAN DEFAULT false,
    active BOOLEAN DEFAULT true,
    stock INTEGER DEFAULT 5,
    weight_g INTEGER DEFAULT 100,
    creator_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 3. COMMANDES
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    shipping_address TEXT,
    items JSONB, -- Contient le tableau des produits achetés
    total NUMERIC,
    shipping_method TEXT,
    payment_method TEXT,
    payment_id TEXT,
    status TEXT DEFAULT 'paid' -- pending, paid, shipped, delivered, cancelled
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- 4. MÉTHODES D'EXPÉDITION
CREATE TABLE IF NOT EXISTS shipping_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    base_price NUMERIC DEFAULT 0,
    price_per_kg NUMERIC DEFAULT 0,
    estimated_days TEXT,
    min_weight NUMERIC DEFAULT 0,
    max_weight NUMERIC DEFAULT 999999,
    is_pickup BOOLEAN DEFAULT false,
    active BOOLEAN DEFAULT true
);
ALTER TABLE shipping_methods ENABLE ROW LEVEL SECURITY;

-- 5. MATÉRIAUX D'IMPRESSION (Calculateur B2B)
CREATE TABLE IF NOT EXISTS printing_materials (
    id TEXT PRIMARY KEY, -- ex: 'pla_standard'
    name TEXT NOT NULL,
    type TEXT, -- FDM ou SLA
    density NUMERIC DEFAULT 1.24,
    cost_per_gram NUMERIC DEFAULT 0.05,
    color_hex TEXT DEFAULT 'FFFFFF',
    active BOOLEAN DEFAULT true
);
ALTER TABLE printing_materials ENABLE ROW LEVEL SECURITY;

-- 6. COUPONS
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT DEFAULT 'percent', -- 'percent' ou 'fixed'
    value NUMERIC NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

-- 7. BLOG / ARTICLES
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    category TEXT DEFAULT 'News',
    image TEXT,
    author TEXT DEFAULT 'Manu',
    read_time TEXT DEFAULT '3 min',
    date TIMESTAMPTZ DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- 8. PARTENAIRES & AVIS & PORTFOLIO (Contenu Vitrine)
CREATE TABLE IF NOT EXISTS partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    logo_url TEXT,
    description TEXT,
    url TEXT,
    display_order INTEGER DEFAULT 0
);
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    role TEXT,
    rating INTEGER DEFAULT 5,
    text TEXT,
    item_purchased TEXT,
    display_date TEXT
);
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    image TEXT
);
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS creators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    bio TEXT,
    avatar_url TEXT,
    banner_url TEXT,
    website_url TEXT,
    social_instagram TEXT
);
ALTER TABLE creators ENABLE ROW LEVEL SECURITY;

-- 9. DEMANDES PROJET (Formulaire Atelier)
CREATE TABLE IF NOT EXISTS project_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    customer_name TEXT,
    customer_email TEXT,
    project_type TEXT,
    description TEXT,
    file_url TEXT,
    is_urgent BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'pending' -- pending, quoted, rejected, completed
);
ALTER TABLE project_requests ENABLE ROW LEVEL SECURITY;

-- 10. NEWSLETTER
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- POLITIQUES DE SÉCURITÉ (RLS POLICIES)
-- ==============================================================================
-- NOTE: Pour cette application CMS "Client-Side", nous utilisons une politique permissive
-- car l'authentification est gérée par le mot de passe Admin dans le frontend.
-- Dans une app Enterprise, nous utiliserions Supabase Auth.
-- Ces politiques permettent d'éviter les alertes de sécurité du dashboard.

-- Politique générique de lecture publique (Tout le monde peut voir le site)
DO $$ BEGIN
  CREATE POLICY "Public Read Access" ON site_config FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON products FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON shipping_methods FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON printing_materials FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON coupons FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON articles FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON partners FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON reviews FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON portfolio FOR SELECT USING (true);
  CREATE POLICY "Public Read Access" ON creators FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Politique d'écriture (INSERT/UPDATE/DELETE)
-- Pour simplifier l'intégration avec AdminTool (qui utilise la clé ANON), on autorise l'écriture.
-- La sécurité est assurée par le mot de passe frontend VITE_ADMIN_PASSWORD.
DO $$ BEGIN
  -- Config & Produits & Blog (Admin)
  CREATE POLICY "Admin Write Access" ON site_config FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Admin Write Access" ON products FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Admin Write Access" ON articles FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Admin Write Access" ON coupons FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Admin Write Access" ON shipping_methods FOR ALL USING (true) WITH CHECK (true);
  CREATE POLICY "Admin Write Access" ON printing_materials FOR ALL USING (true) WITH CHECK (true);
  
  -- Commandes & Demandes (Clients + Admin)
  CREATE POLICY "Public Write Access" ON orders FOR INSERT WITH CHECK (true);
  CREATE POLICY "Admin Update Access" ON orders FOR UPDATE USING (true); -- Seul l'admin update le statut
  CREATE POLICY "Public Read Access" ON orders FOR SELECT USING (true); -- L'admin doit pouvoir lire

  CREATE POLICY "Public Insert Access" ON project_requests FOR INSERT WITH CHECK (true);
  CREATE POLICY "Admin Read Access" ON project_requests FOR SELECT USING (true);

  CREATE POLICY "Public Subscribe" ON newsletter_subscribers FOR INSERT WITH CHECK (true);
  CREATE POLICY "Admin Read Subs" ON newsletter_subscribers FOR SELECT USING (true);

EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ==============================================================================
-- DONE
-- ==============================================================================
