-- ==============================================================================
-- SCHEMA SUPABASE - MANU3D (V3.1 - Ultimate Edition)
-- Script Robuste (Idempotent) : Copiez et Exécutez ce script dans l'éditeur SQL.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. OPTIMISATION PRODUITS (Cross-Selling & SEO)
-- ------------------------------------------------------------------------------

ALTER TABLE products ADD COLUMN IF NOT EXISTS popularity_score int DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS related_ids int[] DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_desc text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold int DEFAULT 2;

-- ------------------------------------------------------------------------------
-- 2. OPTIMISATION COMMANDES (Suivi & Admin)
-- ------------------------------------------------------------------------------

ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS carrier_name text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_notes text;

-- ------------------------------------------------------------------------------
-- 3. GESTION DES COUPONS DE REDUCTION
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  discount_type text CHECK (discount_type IN ('percent', 'fixed')),
  value numeric NOT NULL,
  active boolean DEFAULT true,
  usage_limit int DEFAULT NULL,
  used_count int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Ajout contrainte unique sécurisée pour les coupons
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coupons_code_key') THEN
    ALTER TABLE coupons ADD CONSTRAINT coupons_code_key UNIQUE (code);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS coupons_code_idx ON coupons (code);

-- Sécurité (RLS) : Permettre au site de LIRE les coupons
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'coupons' AND policyname = 'Public read coupons') THEN
    CREATE POLICY "Public read coupons" ON coupons FOR SELECT USING (true);
  END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 4. GESTION NEWSLETTER (Blog)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Ajout contrainte unique sécurisée pour la newsletter
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'newsletter_subscribers_email_key') THEN
    ALTER TABLE newsletter_subscribers ADD CONSTRAINT newsletter_subscribers_email_key UNIQUE (email);
  END IF;
END $$;

-- Sécurité (RLS) : Permettre l'inscription publique
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'newsletter_subscribers' AND policyname = 'Public insert newsletter') THEN
    CREATE POLICY "Public insert newsletter" ON newsletter_subscribers FOR INSERT WITH CHECK (true);
  END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 5. NETTOYAGE DONNÉES (POIDS KG -> G)
-- ------------------------------------------------------------------------------
-- Si des poids sont < 100 (ex: 2kg), on les convertit en grammes (2000g)

UPDATE shipping_methods
SET max_weight = max_weight * 1000
WHERE max_weight < 100 AND max_weight > 0;

UPDATE shipping_methods
SET min_weight = min_weight * 1000
WHERE min_weight < 100 AND min_weight > 0;

UPDATE products
SET weight_g = weight_g * 1000
WHERE weight_g < 10 AND weight_g > 0;

-- ------------------------------------------------------------------------------
-- FIN DU SCRIPT
-- ==============================================================================